// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBRK3ZRb82g10twtxCcJS6bWCncVdteE',
    appId: '1:343363254575:web:c604a51a4a3a962ecac9da',
    messagingSenderId: '343363254575',
    projectId: 'pneumo-ai',
    authDomain: 'pneumo-ai.firebaseapp.com',
    storageBucket: 'pneumo-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP1NGBiWkuAsuJfwJQe3jUfuKu6r-k_Wo',
    appId: '1:343363254575:android:032f75161681f674cac9da',
    messagingSenderId: '343363254575',
    projectId: 'pneumo-ai',
    storageBucket: 'pneumo-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntacT-uHwV56aft6iW8ZguePjyAMaCbA',
    appId: '1:343363254575:ios:35cd993def874f01cac9da',
    messagingSenderId: '343363254575',
    projectId: 'pneumo-ai',
    storageBucket: 'pneumo-ai.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntacT-uHwV56aft6iW8ZguePjyAMaCbA',
    appId: '1:343363254575:ios:35cd993def874f01cac9da',
    messagingSenderId: '343363254575',
    projectId: 'pneumo-ai',
    storageBucket: 'pneumo-ai.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbBRK3ZRb82g10twtxCcJS6bWCncVdteE',
    appId: '1:343363254575:web:18a56b5135dc16d7cac9da',
    messagingSenderId: '343363254575',
    projectId: 'pneumo-ai',
    authDomain: 'pneumo-ai.firebaseapp.com',
    storageBucket: 'pneumo-ai.firebasestorage.app',
  );
}
